### ISSUE TITLE
Impossible to load lib after version 2.0.0

### ISSUE THREAD

**Issue by thomaspoignant** [the-control-group/scim-query-filter-parser-js#4]
I have tried to use the library and after the version 2.0.0, the module is not found when trying to load it in node.

I have this error : 
```
const { compileFilter, compileSorter }  = require('scim-query-filter-parser');
Thrown:
{ Error: Cannot find module 'scim-query-filter-parser'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16) code: 'MODULE_NOT_FOUND' }
```

When doing the same things with the version 1.1.1 works.

**Print screen of what I have test :** 
![image](https://user-images.githubusercontent.com/17908063/68466678-2c5bbd80-0215-11ea-9c0b-1122917b4dd9.png)

**Comment by mike-marcacci** [comment]
Thanks! Fixed in version 2.0.2
