### ISSUE TITLE
Sort is inefficient 

### ISSUE THREAD

**Issue by thomaspoignant** [the-control-group/scim-query-filter-parser-js#5]
The sort functionality is not efficient.
When I try to sort on a set of 1000 resources it takes more than **600ms**.

This GIST (https://gist.github.com/thomaspoignant/a6575ae113cc184e436e9e59001f78a8) allows us to test it.
I have run it multiple time and my results are always slow.

**Comment by thomaspoignant** [comment]
After checking a bit the problem seems to be on this line, it takes forever to compare the values.

https://github.com/the-control-group/scim-query-filter-parser-js/blob/fdb74e9f17b52fd7e9152977e3369495a53771ce/src/util.ts#L14

**Comment by mike-marcacci** [comment]
Indeed, that is unacceptably slow. Do you mind if I add your gist and sample users file to this repo for perf testing (since that's something we should clearly be tracking).

**Comment by thomaspoignant** [comment]
no problem you can use these gists.

**Comment by thomaspoignant** [comment]
I was on node@10.

**Comment by thomaspoignant** [comment]
@mike-marcacci thanks for the fix, but I still have a problem when trying to use the `v2.0.3` with the same gist that I put before.

I have an error like this one : 
```
internal/modules/cjs/loader.js:976
  throw err;
  ^

Error: Cannot find module './Yard'
Require stack:
- /Users/thomaspoignant/Documents/projects/libraries/test-scim-sort/node_modules/scim-query-filter-parser/dist/index.js
- /Users/thomaspoignant/Documents/projects/libraries/test-scim-sort/test.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/thomaspoignant/Documents/projects/libraries/test-scim-sort/node_modules/scim-query-filter-parser/dist/index.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/thomaspoignant/Documents/projects/libraries/test-scim-sort/node_modules/scim-query-filter-parser/dist/index.js',
    '/Users/thomaspoignant/Documents/projects/libraries/test-scim-sort/test.js'
  ]
}
```

I have checked your commits and it looks fine to me if you have any idea 🤷‍♂

**Comment by albehrens** [comment]
I have the same error. Looks like the `/dist` folder is empty (except for `index.js`). Something probably went wrong when publishing to npm.

**Comment by mike-marcacci** [comment]
Indeed, I just went to pull it into my project and discovered the same! I just re-published in a new patch. Let me know if you have any issues.

**Comment by thomaspoignant** [comment]
Thanks a lot that works for me now 👌
